name: Build Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Change directory to android/
        run: cd android

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'oracle'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Install SDL3
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl3-dev

      - name: Build with Gradle
        run: ./gradlew assembleDebug
        working-directory: android

      - name: Upload debug apk
        uses: actions/upload-artifact@v4
        with:
          name: brut-debug
          compression-level: 0
          path: app/build/outputs/apk/debug/