name: Build Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'oracle'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: cd android && chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Install SDL3 from source
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git cmake ninja-build build-essential \
            libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev \
            libxss-dev libxkbcommon-dev libwayland-dev libdrm-dev libgbm-dev \
            libudev-dev libgl1-mesa-dev libdbus-1-dev libasound2-dev libpulse-dev

          git clone https://github.com/libsdl-org/SDL.git
          cd SDL
          mkdir build && cd build
          cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=/usr
          ninja
          sudo ninja install

      - name: Build with Gradle
        run: cd cd android && ./gradlew assembleRelease
        working-directory: android

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: brut
          compression-level: 0
          path: android/app/build/outputs/apk/release/app-release.apk