name: Build C Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install build tools and dependencies
      run: |
        echo "Updating package list and installing required dependencies..."
        sudo apt-get update -y
        sudo apt-get install -y build-essential clang cmake libglfw3-dev libglm-dev

    - name: Give execute permission to LinuxBuild
      run: chmod +x LinuxBuild.sh

    - name: Compile the project
      run: |
        echo "Starting the build process..."
        ./LinuxBuild.sh
        echo "Build finished."
    - name: Upload compiled binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: glcargame
        path: glcargame