name: Build Brut Desktop

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build-desktop:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
          submodules: true

    - name: Install build tools and dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential clang cmake ninja-build \
          libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev \
          libxss-dev libwayland-dev libxkbcommon-dev wayland-protocols libdrm-dev libgl1-mesa-dev

    - name: Give execute permission to Make
      run: chmod +x Make.sh

    - name: Compile the project
      run: |
        echo "Starting the build process..."
        ./Make.sh -d
        echo "Build finished."

    - name: Upload compiled binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: brut-desktop
        path: brut_desktop